export const PixelInfoUpdate = 'PixelInfoUpdate'
export const ListingUpdate = 'ListingUpdate'
export const UndownUpdate = 'UndownUpdate'
export const ResetDrawPixel = 'ResetDrawPixel'
export const RefreshCrowdUndone = 'RefreshCrowdUndone'
